### PR TITLE
don't 'make install' the ipr.h header

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by RhodiumToad** [comment]
Why not?

**Comment by praiskup** [comment]
Maybe I'm wrong, but I thought it's not useful (nobody builds against ipr.h), or?

**Comment by RhodiumToad** [comment]
Extensions that define data types should install sufficient header files to make it possible to build transform modules for them independently. (And likewise, extensions that are PLs should do the same.) This is the primary reason why I put so much effort into allowing extensions to install header files in the first place.

**Comment by praiskup** [comment]
What do you mean by "transform module" and where is it documented?

Background story is that I'd have to create `postgresql-ip4r-devel` package having only this header file.  So I'd like to know what package/software would be built against that installed devel package.

**Comment by praiskup** [comment]
development moved to https://pagure.io/copr/copr/pull-requests, I keep mirror in https://github.com/praiskup/copr.

**Comment by praiskup** [comment]
Uh, wrong PR, sorry.

**Comment by RhodiumToad** [comment]
Transform modules specify how a particular data type is to be handled in a particular PL language. For example, for the contrib/hstore module there are transforms for plperl and plpython that map the hstore value to native perl hashes / python dicts rather than leaving it as a string requiring parsing. See https://www.postgresql.org/docs/current/sql-createtransform.html (there's another thing called "transform" documented in the Extending SQL chapter, but that's unrelated), and contrib/hstore_plperl etc.

A transform module might be provided by the author of the type, the author of the PL, or a third party. To the best of my knowledge nobody is building anything against ip4r (not even me in my own external PL), but the whole point of installing header files is to make it possible for people to do that (now or in the future) without me having to know about it.

As for having a -devel package to install one .h file that may well never be used, I agree that is overkill. But that's your packaging policy, not mine; making an exception to put the .h file in the same package seems reasonable to me (and I've seen that done elsewhere).

**Comment by praiskup** [comment]
Ok, I haven't seen header files in third party module so far, thanks for explanation.

FTR, I've removed the file downstream, and I'll install it to `*-devel` once anybody really needs that.
https://src.fedoraproject.org/rpms/postgresql-ip4r/blob/4d9164b64340f91d530be88f4362c24fc281172b/f/postgresql-ip4r.spec#_37

**Pull request closed without merging**
